- name: Huberman Lab
  type: youtube
  handle: "@hubermanlab"
  vault_path: Health/Huberman

- name: FoundMyFitness
  type: youtube
  handle: "@FoundMyFitness"
  vault_path: Health/Rhonda Patrick

- name: Peter Attia
  type: youtube
  handle: "@PeterAttiaMD"
  vault_path: Health/Peter Attia
